services:
    app:
        restart: unless-stopped
        build:
          context: ./docker
          dockerfile: ./dockerfile
        ports:
            - '${APP_PORT}:80'
        volumes:
            - '.:/var/www/html'
    redis:
        image: redis
        restart: unless-stopped
        ports:
          - "${REDIS_PORT}:6379"
  